import { ProjectDocument, VectorObject, PagePreset, PageOrientation, Unit } from '../types/document';
import { PAGE_PRESETS, getPageDimensions } from './units';

export interface TemplateDefinition {
  id: string;
  name: string;
  category: 'Certificate' | 'Resume' | 'Invoice' | 'Flashcard' | 'PokerCard';
  description: string;
  thumbnailIcon: string;
  preset: PagePreset;
  orientation: PageOrientation;
  unit: Unit;
  createDocument: () => ProjectDocument;
}

// 1. Certificate Template
export function createCertificateTemplate(): ProjectDocument {
  const dims = getPageDimensions('A4', 'portrait');
  return {
    id: 'tpl-certificate-' + Date.now(),
    name: 'Certificate of Achievement',
    version: '1.0.0',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    unit: 'mm',
    page: {
      preset: 'A4',
      width: dims.width,
      height: dims.height,
      orientation: 'portrait',
      margins: { top: 10, right: 10, bottom: 10, left: 10 },
    },
    grid: { show: true, spacing: 10, snap: true },
    snap: { enabled: true, snapToGrid: true, snapToPage: true, snapToObjects: true, thresholdMm: 2.0 },
    objects: [
      {
        id: 'cert-border-outer',
        name: 'Outer Border',
        type: 'rect',
        x: 10,
        y: 10,
        width: 190,
        height: 277,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 1,
        rx: 3,
        ry: 3,
        fill: { type: 'none' },
        stroke: { type: 'solid', color: '#1e3a8a', width: 1.2, opacity: 1 },
      },
      {
        id: 'cert-border-inner',
        name: 'Inner Border',
        type: 'rect',
        x: 13,
        y: 13,
        width: 184,
        height: 271,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 2,
        rx: 1.5,
        ry: 1.5,
        fill: { type: 'none' },
        stroke: { type: 'solid', color: '#d97706', width: 0.5, opacity: 0.9 },
      },
      {
        id: 'cert-banner',
        name: 'Header Banner',
        type: 'rect',
        x: 25,
        y: 28,
        width: 160,
        height: 26,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 3,
        rx: 4,
        ry: 4,
        fill: {
          type: 'linear',
          angle: 90,
          opacity: 1,
          stops: [
            { id: 's1', offset: 0, color: '#1e3a8a', opacity: 1 },
            { id: 's2', offset: 1, color: '#2563eb', opacity: 1 },
          ],
        },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      },
      {
        id: 'cert-title',
        name: 'Certificate Title',
        type: 'text',
        x: 30,
        y: 35,
        width: 150,
        height: 14,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 4,
        text: 'CERTIFICATE OF ACHIEVEMENT',
        fontFamily: 'Inter',
        fontSize: 18,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0.8,
        fill: { type: 'solid', color: '#ffffff', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 1 },
      },
      {
        id: 'cert-subtitle',
        name: 'Presentation Note',
        type: 'text',
        x: 35,
        y: 68,
        width: 140,
        height: 8,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 5,
        text: 'THIS CERTIFICATE IS PROUDLY PRESENTED TO',
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0.5,
        fill: { type: 'solid', color: '#64748b', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 1 },
      },
      {
        id: 'cert-name-placeholder',
        name: 'Recipient Name',
        type: 'text',
        x: 25,
        y: 86,
        width: 160,
        height: 18,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 6,
        text: 'Chirag Sharma',
        fontFamily: 'Inter',
        fontSize: 26,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0.2,
        fill: { type: 'solid', color: '#0f172a', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 1 },
        placeholder: {
          isPlaceholder: true,
          name: 'recipient_name',
          description: 'Full legal name of the recipient or awardee',
          defaultValue: 'Chirag Sharma',
        },
      },
      {
        id: 'cert-divider',
        name: 'Accent Divider Line',
        type: 'line',
        x: 55,
        y: 108,
        width: 100,
        height: 0,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 7,
        x2: 100,
        y2: 0,
        stroke: { type: 'solid', color: '#d97706', width: 0.6, opacity: 1 },
      },
      {
        id: 'cert-course-placeholder',
        name: 'Course Title',
        type: 'text',
        x: 30,
        y: 145,
        width: 150,
        height: 12,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 9,
        text: 'Advanced Vector PDF Architecture',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0.2,
        fill: { type: 'solid', color: '#1d4ed8', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 1 },
        placeholder: {
          isPlaceholder: true,
          name: 'course_title',
          description: 'Title of the certification course or workshop',
          defaultValue: 'Advanced Vector PDF Architecture',
        },
      },
      {
        id: 'cert-seal',
        name: 'Gold Seal Badge',
        type: 'ellipse',
        x: 93,
        y: 172,
        width: 24,
        height: 24,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 10,
        fill: {
          type: 'radial',
          cx: 0.5,
          cy: 0.5,
          opacity: 1,
          stops: [
            { id: 's1', offset: 0, color: '#fef08a', opacity: 1 },
            { id: 's2', offset: 0.7, color: '#f59e0b', opacity: 1 },
            { id: 's3', offset: 1, color: '#b45309', opacity: 1 },
          ],
        },
        stroke: { type: 'solid', color: '#78350f', width: 0.5, opacity: 1 },
      },
      {
        id: 'cert-date',
        name: 'Issue Date',
        type: 'text',
        x: 35,
        y: 228,
        width: 45,
        height: 6,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 11,
        text: 'September 2026',
        fontFamily: 'Inter',
        fontSize: 9,
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#1e293b', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 1 },
        placeholder: {
          isPlaceholder: true,
          name: 'issue_date',
          description: 'Date of issuance',
          defaultValue: 'September 2026',
        },
      },
      {
        id: 'cert-id',
        name: 'Certificate Serial ID',
        type: 'text',
        x: 60,
        y: 265,
        width: 90,
        height: 5,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 12,
        text: 'ID: CERT-2026-00918',
        fontFamily: 'Inter',
        fontSize: 7,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0.5,
        fill: { type: 'solid', color: '#94a3b8', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 1 },
        placeholder: {
          isPlaceholder: true,
          name: 'certificate_id',
          description: 'Unique verification serial or certificate number',
          defaultValue: 'ID: CERT-2026-00918',
        },
      },
    ],
  };
}

// 2. Professional Resume Template (A4 Portrait)
export function createResumeTemplate(): ProjectDocument {
  const dims = getPageDimensions('A4', 'portrait');
  return {
    id: 'tpl-resume-' + Date.now(),
    name: 'Executive Resume',
    version: '1.0.0',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    unit: 'mm',
    page: {
      preset: 'A4',
      width: dims.width,
      height: dims.height,
      orientation: 'portrait',
      margins: { top: 12, right: 12, bottom: 12, left: 12 },
    },
    grid: { show: true, spacing: 5, snap: true },
    snap: { enabled: true, snapToGrid: true, snapToPage: true, snapToObjects: true, thresholdMm: 1.5 },
    objects: [
      // Top header bar
      {
        id: 'res-header-bg',
        name: 'Header Accent',
        type: 'rect',
        x: 12,
        y: 12,
        width: 186,
        height: 38,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 1,
        rx: 2,
        ry: 2,
        fill: { type: 'solid', color: '#0f172a', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      },
      // Full Name
      {
        id: 'res-name',
        name: 'Full Name',
        type: 'text',
        x: 18,
        y: 18,
        width: 120,
        height: 12,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 2,
        text: 'Alex Morgan',
        fontFamily: 'Inter',
        fontSize: 22,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.1,
        letterSpacing: 0.3,
        fill: { type: 'solid', color: '#ffffff', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'full_name',
          description: 'Candidate full legal name',
          defaultValue: 'Alex Morgan',
        },
      },
      // Job Title
      {
        id: 'res-role',
        name: 'Job Title',
        type: 'text',
        x: 18,
        y: 33,
        width: 120,
        height: 8,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 3,
        text: 'Principal Software Architect & Systems Designer',
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0.4,
        fill: { type: 'solid', color: '#38bdf8', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'job_title',
          description: 'Current professional title / headline',
          defaultValue: 'Principal Software Architect',
        },
      },
      // Contact Info Line
      {
        id: 'res-contact',
        name: 'Contact Info',
        type: 'text',
        x: 140,
        y: 18,
        width: 54,
        height: 26,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 4,
        text: 'alex@example.com\n+1 (555) 234-5678\nSan Francisco, CA\ngithub.com/alexm',
        fontFamily: 'Inter',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'right',
        lineHeight: 1.4,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#cbd5e1', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'contact_details',
          description: 'Email, phone, location, and portfolio link',
          defaultValue: 'alex@example.com\n+1 (555) 234-5678\nSan Francisco, CA',
        },
      },
      // Section: Professional Summary
      {
        id: 'res-sec-summary-title',
        name: 'Summary Title',
        type: 'text',
        x: 12,
        y: 56,
        width: 186,
        height: 6,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 5,
        text: 'PROFESSIONAL SUMMARY',
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0.8,
        fill: { type: 'solid', color: '#0284c7', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      },
      {
        id: 'res-sec-summary-line',
        name: 'Summary Divider',
        type: 'line',
        x: 12,
        y: 63,
        width: 186,
        height: 0,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 6,
        x2: 186,
        y2: 0,
        stroke: { type: 'solid', color: '#0284c7', width: 0.4, opacity: 0.8 },
      },
      {
        id: 'res-summary-body',
        name: 'Summary Body',
        type: 'text',
        x: 12,
        y: 66,
        width: 186,
        height: 18,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 7,
        text: 'Accomplished engineering leader with 10+ years specializing in distributed high-performance cloud architectures, browser-based vector compilation, and precision layout engines. Proven track record scaling products from zero to millions of users with rock-solid reliability.',
        fontFamily: 'Inter',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.4,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#334155', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'professional_summary',
          description: 'A punchy 3-4 sentence professional executive summary',
          defaultValue: 'Accomplished engineering leader with 10+ years specializing in distributed systems...',
        },
      },
      // Section: Experience
      {
        id: 'res-sec-exp-title',
        name: 'Experience Title',
        type: 'text',
        x: 12,
        y: 92,
        width: 186,
        height: 6,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 8,
        text: 'WORK EXPERIENCE',
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0.8,
        fill: { type: 'solid', color: '#0284c7', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      },
      {
        id: 'res-sec-exp-line',
        name: 'Exp Divider',
        type: 'line',
        x: 12,
        y: 99,
        width: 186,
        height: 0,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 9,
        x2: 186,
        y2: 0,
        stroke: { type: 'solid', color: '#0284c7', width: 0.4, opacity: 0.8 },
      },
      // Experience 1
      {
        id: 'res-job1-header',
        name: 'Job 1 Header',
        type: 'text',
        x: 12,
        y: 104,
        width: 186,
        height: 6,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 10,
        text: 'Staff Systems Architect • VectorFlow Inc. (2022 - Present)',
        fontFamily: 'Inter',
        fontSize: 9.5,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#0f172a', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'job_1_header',
          description: 'Title, company name, and employment dates for role 1',
          defaultValue: 'Staff Systems Architect • VectorFlow Inc. (2022 - Present)',
        },
      },
      {
        id: 'res-job1-desc',
        name: 'Job 1 Description',
        type: 'text',
        x: 12,
        y: 112,
        width: 186,
        height: 22,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 11,
        text: '• Directed architecture of zero-latency vector rendering pipeline processing 50M daily requests.\n• Reduced memory overhead by 42% through optimized SVG-to-PDF binary stream compression.\n• Mentored team of 14 senior engineers across distributed frontend and core graphics teams.',
        fontFamily: 'Inter',
        fontSize: 8.5,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.45,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#334155', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'job_1_bullets',
          description: 'Bullet points detailing key achievements in role 1',
          defaultValue: '• Directed architecture of zero-latency vector rendering pipeline...',
        },
      },
      // Experience 2
      {
        id: 'res-job2-header',
        name: 'Job 2 Header',
        type: 'text',
        x: 12,
        y: 140,
        width: 186,
        height: 6,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 12,
        text: 'Senior Full Stack Lead • CloudPrint Labs (2018 - 2022)',
        fontFamily: 'Inter',
        fontSize: 9.5,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#0f172a', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'job_2_header',
          description: 'Title, company name, and employment dates for role 2',
          defaultValue: 'Senior Full Stack Lead • CloudPrint Labs (2018 - 2022)',
        },
      },
      {
        id: 'res-job2-desc',
        name: 'Job 2 Description',
        type: 'text',
        x: 12,
        y: 148,
        width: 186,
        height: 22,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 13,
        text: '• Built browser-based design suite empowering 250,000 active print shops worldwide.\n• Pioneered automated batch PDF layout templating engine cutting document prep time by 75%.\n• Designed multi-threaded canvas renderer handling complex vector illustrations seamlessly.',
        fontFamily: 'Inter',
        fontSize: 8.5,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.45,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#334155', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'job_2_bullets',
          description: 'Bullet points detailing key achievements in role 2',
          defaultValue: '• Built browser-based design suite empowering 250,000 print shops...',
        },
      },
      // Section: Skills & Education
      {
        id: 'res-sec-skills-title',
        name: 'Skills Title',
        type: 'text',
        x: 12,
        y: 178,
        width: 186,
        height: 6,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 14,
        text: 'CORE COMPETENCIES & TECHNOLOGIES',
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0.8,
        fill: { type: 'solid', color: '#0284c7', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      },
      {
        id: 'res-sec-skills-line',
        name: 'Skills Divider',
        type: 'line',
        x: 12,
        y: 185,
        width: 186,
        height: 0,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 15,
        x2: 186,
        y2: 0,
        stroke: { type: 'solid', color: '#0284c7', width: 0.4, opacity: 0.8 },
      },
      {
        id: 'res-skills-content',
        name: 'Skills List',
        type: 'text',
        x: 12,
        y: 189,
        width: 186,
        height: 16,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 16,
        text: 'Languages: TypeScript, Rust, Python, Go, C++, SQL\nFrontend & Vector: React, WebGL, SVG, Canvas API, PostScript, jsPDF\nCloud & Architecture: Kubernetes, Docker, Microservices, CI/CD, AWS, Redis',
        fontFamily: 'Inter',
        fontSize: 8.5,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.45,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#334155', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'technical_skills',
          description: 'Key technical competencies grouped by category',
          defaultValue: 'Languages: TypeScript, Rust, Python...',
        },
      },
      // Education
      {
        id: 'res-sec-edu-title',
        name: 'Education Title',
        type: 'text',
        x: 12,
        y: 215,
        width: 186,
        height: 6,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 17,
        text: 'EDUCATION',
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0.8,
        fill: { type: 'solid', color: '#0284c7', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      },
      {
        id: 'res-sec-edu-line',
        name: 'Edu Divider',
        type: 'line',
        x: 12,
        y: 222,
        width: 186,
        height: 0,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 18,
        x2: 186,
        y2: 0,
        stroke: { type: 'solid', color: '#0284c7', width: 0.4, opacity: 0.8 },
      },
      {
        id: 'res-edu-content',
        name: 'Education Info',
        type: 'text',
        x: 12,
        y: 226,
        width: 186,
        height: 12,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 19,
        text: 'B.S. in Computer Science & Engineering (Summa Cum Laude)\nStanford University • Dean\'s Honor List',
        fontFamily: 'Inter',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.4,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#334155', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'education_details',
          description: 'Degree, university name, and academic distinctions',
          defaultValue: 'B.S. in Computer Science & Engineering • Stanford University',
        },
      },
    ],
  };
}

// 3. Commercial Bill / Invoice Template (A4 Portrait)
export function createInvoiceTemplate(): ProjectDocument {
  const dims = getPageDimensions('A4', 'portrait');
  return {
    id: 'tpl-invoice-' + Date.now(),
    name: 'Commercial Invoice',
    version: '1.0.0',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    unit: 'mm',
    page: {
      preset: 'A4',
      width: dims.width,
      height: dims.height,
      orientation: 'portrait',
      margins: { top: 12, right: 12, bottom: 12, left: 12 },
    },
    grid: { show: true, spacing: 5, snap: true },
    snap: { enabled: true, snapToGrid: true, snapToPage: true, snapToObjects: true, thresholdMm: 1.5 },
    objects: [
      // Top Brand Box
      {
        id: 'inv-brand-bg',
        name: 'Brand Accent',
        type: 'rect',
        x: 12,
        y: 12,
        width: 10,
        height: 10,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 1,
        rx: 2,
        ry: 2,
        fill: { type: 'solid', color: '#2563eb', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      },
      // Company Name
      {
        id: 'inv-company-name',
        name: 'Company Name',
        type: 'text',
        x: 26,
        y: 13,
        width: 90,
        height: 8,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 2,
        text: 'ACME Digital Solutions Ltd.',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#0f172a', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'company_name',
          description: 'Issuing company or freelance business name',
          defaultValue: 'ACME Digital Solutions Ltd.',
        },
      },
      // INVOICE Header Right
      {
        id: 'inv-title-text',
        name: 'Invoice Heading',
        type: 'text',
        x: 130,
        y: 12,
        width: 68,
        height: 10,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 3,
        text: 'INVOICE',
        fontFamily: 'Inter',
        fontSize: 20,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'right',
        lineHeight: 1.2,
        letterSpacing: 1.5,
        fill: { type: 'solid', color: '#1e3a8a', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      },
      // Invoice Meta info
      {
        id: 'inv-meta-text',
        name: 'Invoice Meta',
        type: 'text',
        x: 130,
        y: 26,
        width: 68,
        height: 16,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 4,
        text: 'Invoice #: INV-2026-0842\nDate: 2026-09-30\nDue Date: 2026-10-15',
        fontFamily: 'Inter',
        fontSize: 8.5,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'right',
        lineHeight: 1.4,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#475569', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'invoice_meta',
          description: 'Invoice number, issuance date, and payment due date',
          defaultValue: 'Invoice #: INV-2026-0842\nDate: 2026-09-30\nDue Date: 2026-10-15',
        },
      },
      // Divider
      {
        id: 'inv-div-1',
        name: 'Header Line',
        type: 'line',
        x: 12,
        y: 48,
        width: 186,
        height: 0,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 5,
        x2: 186,
        y2: 0,
        stroke: { type: 'solid', color: '#e2e8f0', width: 0.5, opacity: 1 },
      },
      // Bill To Section
      {
        id: 'inv-bill-to-label',
        name: 'Bill To Label',
        type: 'text',
        x: 12,
        y: 53,
        width: 90,
        height: 5,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 6,
        text: 'BILLED TO:',
        fontFamily: 'Inter',
        fontSize: 8,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0.5,
        fill: { type: 'solid', color: '#64748b', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      },
      {
        id: 'inv-client-info',
        name: 'Client Details',
        type: 'text',
        x: 12,
        y: 60,
        width: 90,
        height: 16,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 7,
        text: 'Global Enterprise Corp\nAttn: Accounts Payable\n100 Market Street, Suite 500\nSan Francisco, CA 94105',
        fontFamily: 'Inter',
        fontSize: 8.5,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.35,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#1e293b', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'client_details',
          description: 'Client name, department, and mailing address',
          defaultValue: 'Global Enterprise Corp\nAttn: Accounts Payable\n100 Market St',
        },
      },
      // Table Header Row Background
      {
        id: 'inv-table-hdr-bg',
        name: 'Table Header Bar',
        type: 'rect',
        x: 12,
        y: 84,
        width: 186,
        height: 9,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 8,
        rx: 1,
        ry: 1,
        fill: { type: 'solid', color: '#f1f5f9', opacity: 1 },
        stroke: { type: 'solid', color: '#cbd5e1', width: 0.3, opacity: 1 },
      },
      // Table Header Text
      {
        id: 'inv-th-text',
        name: 'Table Column Headers',
        type: 'text',
        x: 16,
        y: 86.5,
        width: 178,
        height: 5,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 9,
        text: 'ITEM DESCRIPTION                                               QTY       RATE        AMOUNT',
        fontFamily: 'Inter',
        fontSize: 7.5,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0.4,
        fill: { type: 'solid', color: '#334155', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      },
      // Item 1
      {
        id: 'inv-item-1',
        name: 'Item Row 1',
        type: 'text',
        x: 16,
        y: 98,
        width: 178,
        height: 8,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 10,
        text: 'Vector PDF Template Engine Architecture              1       $4,500.00    $4,500.00',
        fontFamily: 'Inter',
        fontSize: 8.5,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#1e293b', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'item_1_line',
          description: 'Line item 1 description, quantity, unit rate, and total',
          defaultValue: 'Vector PDF Template Engine Architecture              1       $4,500.00    $4,500.00',
        },
      },
      // Item 2
      {
        id: 'inv-item-2',
        name: 'Item Row 2',
        type: 'text',
        x: 16,
        y: 110,
        width: 178,
        height: 8,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 11,
        text: 'Dynamic Magnetic Snapping & Alight Controller     1       $2,200.00    $2,200.00',
        fontFamily: 'Inter',
        fontSize: 8.5,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#1e293b', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'item_2_line',
          description: 'Line item 2 description, quantity, unit rate, and total',
          defaultValue: 'Dynamic Magnetic Snapping & Alight Controller     1       $2,200.00    $2,200.00',
        },
      },
      // Item 3
      {
        id: 'inv-item-3',
        name: 'Item Row 3',
        type: 'text',
        x: 16,
        y: 122,
        width: 178,
        height: 8,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 12,
        text: 'Touch Tablet Gestures & Multi-Page Support         1       $1,800.00    $1,800.00',
        fontFamily: 'Inter',
        fontSize: 8.5,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#1e293b', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'item_3_line',
          description: 'Line item 3 description, quantity, unit rate, and total',
          defaultValue: 'Touch Tablet Gestures & Multi-Page Support         1       $1,800.00    $1,800.00',
        },
      },
      // Summary Box Background
      {
        id: 'inv-summary-bg',
        name: 'Total Due Box',
        type: 'rect',
        x: 120,
        y: 142,
        width: 78,
        height: 32,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 13,
        rx: 2,
        ry: 2,
        fill: { type: 'solid', color: '#f8fafc', opacity: 1 },
        stroke: { type: 'solid', color: '#e2e8f0', width: 0.5, opacity: 1 },
      },
      // Summary Breakdown Text
      {
        id: 'inv-summary-text',
        name: 'Total Breakdown',
        type: 'text',
        x: 124,
        y: 146,
        width: 70,
        height: 24,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 14,
        text: 'Subtotal:                      $8,500.00\nTax (8.5%):                     $722.50\nTOTAL DUE:                $9,222.50',
        fontFamily: 'Inter',
        fontSize: 8.5,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.45,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#0f172a', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'total_due_summary',
          description: 'Subtotal, tax calculation, and final grand total due',
          defaultValue: 'Subtotal:                      $8,500.00\nTax (8.5%):                     $722.50\nTOTAL DUE:                $9,222.50',
        },
      },
      // Payment Terms & Wire Instructions
      {
        id: 'inv-terms',
        name: 'Payment Instructions',
        type: 'text',
        x: 12,
        y: 190,
        width: 140,
        height: 18,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 15,
        text: 'Payment Terms: Net 15 days from invoice date.\nWire Transfer: Silicon Valley Bank • Account: 9876543210 • Routing: 121000358\nThank you for your business!',
        fontFamily: 'Inter',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.4,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#64748b', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      },
    ],
  };
}

// 4. YaadCard 27 Flashcards on A3 Sheet (5cm × 9.5cm • 9 Columns × 3 Rows)
export function createYaadCardA3SheetTemplate(): ProjectDocument {
  // Exactly A3 Landscape: 420mm x 297mm
  const cardW = 44; // mm (fits comfortably within 420mm with spacing)
  const cardH = 88; // mm (fits within 297mm across 3 rows)
  const cols = 9;
  const rows = 3;
  const startX = 11;
  const startY = 16;
  const gapX = 1.2;
  const gapY = 3.5;

  const objects: VectorObject[] = [
    // Top Sheet Header
    {
      id: 'yc-sheet-header',
      name: 'A3 Sheet Banner',
      type: 'text',
      x: 12,
      y: 6,
      width: 396,
      height: 6,
      rotation: 0,
      opacity: 1,
      locked: true,
      visible: true,
      zIndex: 1,
      text: 'YAADCARD™ FLASHCARD DECK • 27 CARDS PER A3 SHEET (5cm × 9.5cm FORMAT) • CUT ALONG DOTTED LINES',
      fontFamily: 'Inter',
      fontSize: 8,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textAlign: 'center',
      lineHeight: 1.2,
      letterSpacing: 0.8,
      fill: { type: 'solid', color: '#64748b', opacity: 1 },
      stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
    },
  ];

  let zIdx = 2;
  let cardNum = 1;

  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const cx = startX + c * (cardW + gapX);
      const cy = startY + r * (cardH + gapY);
      const numStr = String(cardNum).padStart(2, '0');
      const cardGroupId = `yc-card-group-${cardNum}`;
      const linkDeckId = 'yc-deck-27';

      // Card Outer Boundary with Cut Border
      objects.push({
        id: `yc-card-box-${cardNum}`,
        name: `Card #${numStr} Cut Border`,
        type: 'rect',
        groupId: cardGroupId,
        linkGroupId: linkDeckId,
        linkSlotId: 'slot-cut-border',
        x: Number(cx.toFixed(2)),
        y: Number(cy.toFixed(2)),
        width: cardW,
        height: cardH,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: zIdx++,
        rx: 1.5,
        ry: 1.5,
        fill: { type: 'solid', color: '#ffffff', opacity: 1 },
        stroke: { type: 'solid', color: '#94a3b8', width: 0.35, opacity: 0.8, dashArray: '1.5,1.5' },
      });

      // Card Category Pill Header
      objects.push({
        id: `yc-card-cat-${cardNum}`,
        name: `Card #${numStr} Category Pill`,
        type: 'rect',
        groupId: cardGroupId,
        linkGroupId: linkDeckId,
        linkSlotId: 'slot-cat-pill',
        x: Number((cx + 2.5).toFixed(2)),
        y: Number((cy + 2.5).toFixed(2)),
        width: cardW - 5,
        height: 6,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: zIdx++,
        rx: 1,
        ry: 1,
        fill: { type: 'solid', color: r === 0 ? '#eff6ff' : r === 1 ? '#f0fdf4' : '#faf5ff', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      });

      // Card Category Text
      objects.push({
        id: `yc-card-cat-text-${cardNum}`,
        name: `Card #${numStr} Category Text`,
        type: 'text',
        groupId: cardGroupId,
        linkGroupId: linkDeckId,
        linkSlotId: 'slot-cat-text',
        x: Number((cx + 3.5).toFixed(2)),
        y: Number((cy + 4.2).toFixed(2)),
        width: cardW - 7,
        height: 4,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: zIdx++,
        text: `Concept Group ${r + 1} • #${numStr}`,
        fontFamily: 'Inter',
        fontSize: 5.5,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0.2,
        fill: { type: 'solid', color: r === 0 ? '#1d4ed8' : r === 1 ? '#15803d' : '#7e22ce', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      });

      // Card Main Concept / Question
      objects.push({
        id: `yc-card-title-${cardNum}`,
        name: `Card #${numStr} Title`,
        type: 'text',
        groupId: cardGroupId,
        linkGroupId: linkDeckId,
        linkSlotId: 'slot-title-text',
        x: Number((cx + 3).toFixed(2)),
        y: Number((cy + 12).toFixed(2)),
        width: cardW - 6,
        height: 12,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: zIdx++,
        text: cardNum === 1 ? 'Time Value of Money' : cardNum === 2 ? 'Capital Asset Pricing' : `High-Yield Topic ${cardNum}`,
        fontFamily: 'Inter',
        fontSize: 8,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#0f172a', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: `card_${numStr}_title`,
          description: `Key term or concept title for flashcard #${numStr}`,
          defaultValue: `Concept ${numStr}`,
        },
      });

      // Card Tagline / Hook
      objects.push({
        id: `yc-card-tag-${cardNum}`,
        name: `Card #${numStr} Tagline`,
        type: 'text',
        groupId: cardGroupId,
        linkGroupId: linkDeckId,
        linkSlotId: 'slot-tag-text',
        x: Number((cx + 3).toFixed(2)),
        y: Number((cy + 25).toFixed(2)),
        width: cardW - 6,
        height: 8,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: zIdx++,
        text: 'A rupee today is worth more than tomorrow.',
        fontFamily: 'Inter',
        fontSize: 5.5,
        fontWeight: '500',
        fontStyle: 'italic',
        textAlign: 'left',
        lineHeight: 1.25,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#475569', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: `card_${numStr}_tagline`,
          description: `Punchy 1-line hook for card #${numStr}`,
          defaultValue: 'Essential rule or definition.',
        },
      });

      // Card Summary / Body explanation
      objects.push({
        id: `yc-card-body-${cardNum}`,
        name: `Card #${numStr} Summary`,
        type: 'text',
        groupId: cardGroupId,
        linkGroupId: linkDeckId,
        linkSlotId: 'slot-body-text',
        x: Number((cx + 3).toFixed(2)),
        y: Number((cy + 34).toFixed(2)),
        width: cardW - 6,
        height: 28,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: zIdx++,
        text: '• Money earns interest over time.\n• PV = FV / (1 + r)^n\n• Core formula for NPV & discounted cash flow modeling in exams.',
        fontFamily: 'Inter',
        fontSize: 5.5,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.35,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#334155', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: `card_${numStr}_summary`,
          description: `Key memory points and formulas for card #${numStr}`,
          defaultValue: '• Key formula and bullet explanation.',
        },
      });

      // Card Bottom Formula / Mnemonic Box
      objects.push({
        id: `yc-card-tipbox-${cardNum}`,
        name: `Card #${numStr} Mnemonic Box`,
        type: 'rect',
        groupId: cardGroupId,
        linkGroupId: linkDeckId,
        linkSlotId: 'slot-tip-box',
        x: Number((cx + 2.5).toFixed(2)),
        y: Number((cy + 68).toFixed(2)),
        width: cardW - 5,
        height: 16,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: zIdx++,
        rx: 1,
        ry: 1,
        fill: { type: 'solid', color: '#f8fafc', opacity: 1 },
        stroke: { type: 'solid', color: '#cbd5e1', width: 0.3, opacity: 1 },
      });

      objects.push({
        id: `yc-card-tip-${cardNum}`,
        name: `Card #${numStr} Tip Text`,
        type: 'text',
        groupId: cardGroupId,
        linkGroupId: linkDeckId,
        linkSlotId: 'slot-tip-text',
        x: Number((cx + 3.5).toFixed(2)),
        y: Number((cy + 71).toFixed(2)),
        width: cardW - 7,
        height: 12,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: zIdx++,
        text: 'TIP: Higher discount rate (r) yields lower present value (PV).',
        fontFamily: 'Inter',
        fontSize: 5,
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.25,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#0284c7', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      });

      cardNum++;
    }
  }

  return {
    id: 'tpl-yaadcard-a3-' + Date.now(),
    name: 'YaadCard 27-Card A3 Flashcard Sheet (5cm × 9.5cm)',
    version: '1.0.0',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    unit: 'mm',
    page: {
      preset: 'A3',
      width: 420,
      height: 297,
      orientation: 'landscape',
      margins: { top: 10, right: 10, bottom: 10, left: 10 },
    },
    grid: { show: true, spacing: 5, snap: true },
    snap: { enabled: true, snapToGrid: true, snapToPage: true, snapToObjects: true, thresholdMm: 1.5 },
    syncLinkedDuplicates: true,
    objects,
  };
}

// 5. Single YaadCard Flashcard Template (50mm × 95mm / 5cm × 9.5cm)
export function createYaadCardSingleTemplate(): ProjectDocument {
  return {
    id: 'tpl-yaadcard-single-' + Date.now(),
    name: 'YaadCard Flashcard (5cm × 9.5cm)',
    version: '1.0.0',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    unit: 'mm',
    page: {
      preset: 'YaadCard5x9.5',
      width: 50,
      height: 95,
      orientation: 'portrait',
      margins: { top: 3, right: 3, bottom: 3, left: 3 },
    },
    grid: { show: true, spacing: 5, snap: true },
    snap: { enabled: true, snapToGrid: true, snapToPage: true, snapToObjects: true, thresholdMm: 1.5 },
    objects: [
      // Border
      {
        id: 'yc-single-border',
        name: 'Card Border',
        type: 'rect',
        x: 2,
        y: 2,
        width: 46,
        height: 91,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 1,
        rx: 2,
        ry: 2,
        fill: { type: 'solid', color: '#ffffff', opacity: 1 },
        stroke: { type: 'solid', color: '#3b82f6', width: 0.6, opacity: 1 },
      },
      // Category pill
      {
        id: 'yc-single-cat-bg',
        name: 'Category Header Pill',
        type: 'rect',
        x: 4,
        y: 4,
        width: 42,
        height: 7,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 2,
        rx: 1.5,
        ry: 1.5,
        fill: { type: 'solid', color: '#1e3a8a', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      },
      {
        id: 'yc-single-cat-text',
        name: 'Category Name',
        type: 'text',
        x: 6,
        y: 6,
        width: 38,
        height: 5,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 3,
        text: 'CORPORATE FINANCE • #01',
        fontFamily: 'Inter',
        fontSize: 6.5,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0.5,
        fill: { type: 'solid', color: '#ffffff', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'card_category',
          description: 'Flashcard subject category and deck number',
          defaultValue: 'CORPORATE FINANCE • #01',
        },
      },
      // Concept Title
      {
        id: 'yc-single-title',
        name: 'Concept Title',
        type: 'text',
        x: 4,
        y: 15,
        width: 42,
        height: 12,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 4,
        text: 'Time Value of Money',
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#0f172a', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'card_title',
          description: 'Key keyword or concept title of the flashcard',
          defaultValue: 'Time Value of Money',
        },
      },
      // Tagline
      {
        id: 'yc-single-tag',
        name: 'Tagline',
        type: 'text',
        x: 4,
        y: 29,
        width: 42,
        height: 8,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 5,
        text: 'A rupee today is worth more than a rupee tomorrow.',
        fontFamily: 'Inter',
        fontSize: 6.5,
        fontWeight: '500',
        fontStyle: 'italic',
        textAlign: 'center',
        lineHeight: 1.3,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#475569', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'card_tagline',
          description: 'A punchy memorable definition or hook',
          defaultValue: 'A rupee today is worth more than a rupee tomorrow.',
        },
      },
      // Explanation Body
      {
        id: 'yc-single-body',
        name: 'Concept Body & Points',
        type: 'text',
        x: 4,
        y: 39,
        width: 42,
        height: 26,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 6,
        text: '• Core principle: Money earns compound interest through reinvestment.\n• Present Value Formula:\n  PV = FV / (1 + r)^n\n• Future Value Formula:\n  FV = PV × (1 + r)^n',
        fontFamily: 'Inter',
        fontSize: 6.5,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.4,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#1e293b', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'card_body',
          description: 'Detailed bullet points and core equations',
          defaultValue: '• Core principle: Money earns compound interest...',
        },
      },
      // Mnemonic / Tip Callout Box
      {
        id: 'yc-single-tip-bg',
        name: 'Mnemonic Callout Box',
        type: 'rect',
        x: 4,
        y: 70,
        width: 42,
        height: 18,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 7,
        rx: 1.5,
        ry: 1.5,
        fill: { type: 'solid', color: '#f0fdf4', opacity: 1 },
        stroke: { type: 'solid', color: '#86efac', width: 0.4, opacity: 1 },
      },
      {
        id: 'yc-single-tip-text',
        name: 'Mnemonic Text',
        type: 'text',
        x: 6,
        y: 73,
        width: 38,
        height: 12,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 8,
        text: 'MEMORY HOOK: Higher rate (r) or longer time (n) exponentially shrinks Present Value.',
        fontFamily: 'Inter',
        fontSize: 6,
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 1.3,
        letterSpacing: 0,
        fill: { type: 'solid', color: '#15803d', opacity: 1 },
        stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
        placeholder: {
          isPlaceholder: true,
          name: 'card_mnemonic',
          description: 'Quick exam trick or memory hook',
          defaultValue: 'MEMORY HOOK: Higher rate exponentially shrinks PV.',
        },
      },
    ],
  };
}

// 6. Creator Poker Card Template (63.5mm × 88.9mm / 2.5" × 3.5" with Two Sides / Multi-Page)
export function createPokerCardTemplate(): ProjectDocument {
  // Page 1: Front Side Objects
  const frontObjects: VectorObject[] = [
    // Outer border
    {
      id: 'poker-front-border',
      name: 'Card Border (Front)',
      type: 'rect',
      x: 3,
      y: 3,
      width: 57.5,
      height: 82.9,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      zIndex: 1,
      pageId: 'page-front',
      rx: 3.5,
      ry: 3.5,
      fill: {
        type: 'linear',
        angle: 135,
        opacity: 1,
        stops: [
          { id: 's1', offset: 0, color: '#1e1b4b', opacity: 1 },
          { id: 's2', offset: 1, color: '#312e81', opacity: 1 },
        ],
      },
      stroke: { type: 'solid', color: '#fbbf24', width: 0.8, opacity: 1 },
    },
    // Top badge
    {
      id: 'poker-front-cat',
      name: 'Category Header',
      type: 'text',
      x: 6,
      y: 9,
      width: 51.5,
      height: 6,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      zIndex: 2,
      pageId: 'page-front',
      text: 'FINANCE & RISK • #01',
      fontFamily: 'Inter',
      fontSize: 7,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textAlign: 'center',
      lineHeight: 1.2,
      letterSpacing: 0.8,
      fill: { type: 'solid', color: '#fbbf24', opacity: 1 },
      stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      placeholder: {
        isPlaceholder: true,
        name: 'front_category',
        description: 'Subject and card number on front of poker card',
        defaultValue: 'FINANCE & RISK • #01',
      },
    },
    // Center Emblem Badge circle
    {
      id: 'poker-front-emblem',
      name: 'Central Emblem Ring',
      type: 'ellipse',
      x: 21.75,
      y: 22,
      width: 20,
      height: 20,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      zIndex: 3,
      pageId: 'page-front',
      fill: { type: 'none' },
      stroke: { type: 'solid', color: '#fbbf24', width: 0.6, opacity: 0.8 },
    },
    // Main Concept Title
    {
      id: 'poker-front-title',
      name: 'Front Concept Title',
      type: 'text',
      x: 6,
      y: 50,
      width: 51.5,
      height: 18,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      zIndex: 4,
      pageId: 'page-front',
      text: 'Capital Asset Pricing Model\n(CAPM)',
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textAlign: 'center',
      lineHeight: 1.3,
      letterSpacing: 0.2,
      fill: { type: 'solid', color: '#ffffff', opacity: 1 },
      stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      placeholder: {
        isPlaceholder: true,
        name: 'front_title',
        description: 'Primary concept or question name on front side',
        defaultValue: 'Capital Asset Pricing Model (CAPM)',
      },
    },
    // Front footer label
    {
      id: 'poker-front-footer',
      name: 'Front Footer Note',
      type: 'text',
      x: 6,
      y: 76,
      width: 51.5,
      height: 5,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      zIndex: 5,
      pageId: 'page-front',
      text: 'YAADCARD CREATOR • FLIP FOR SOLUTION ➔',
      fontFamily: 'Inter',
      fontSize: 5,
      fontWeight: '600',
      fontStyle: 'normal',
      textAlign: 'center',
      lineHeight: 1.2,
      letterSpacing: 0.5,
      fill: { type: 'solid', color: '#94a3b8', opacity: 1 },
      stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
    },
  ];

  // Page 2: Back Side Objects
  const backObjects: VectorObject[] = [
    // Outer border
    {
      id: 'poker-back-border',
      name: 'Card Border (Back)',
      type: 'rect',
      x: 3,
      y: 3,
      width: 57.5,
      height: 82.9,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      zIndex: 1,
      pageId: 'page-back',
      rx: 3.5,
      ry: 3.5,
      fill: { type: 'solid', color: '#ffffff', opacity: 1 },
      stroke: { type: 'solid', color: '#312e81', width: 0.6, opacity: 1 },
    },
    // Back Title
    {
      id: 'poker-back-title',
      name: 'Back Title',
      type: 'text',
      x: 6,
      y: 6,
      width: 51.5,
      height: 8,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      zIndex: 2,
      pageId: 'page-back',
      text: 'CAPM Formula & Analysis',
      fontFamily: 'Inter',
      fontSize: 9,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textAlign: 'center',
      lineHeight: 1.2,
      letterSpacing: 0,
      fill: { type: 'solid', color: '#1e1b4b', opacity: 1 },
      stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      placeholder: {
        isPlaceholder: true,
        name: 'back_title',
        description: 'Title of the answer on back side',
        defaultValue: 'CAPM Formula & Analysis',
      },
    },
    // Back Tagline
    {
      id: 'poker-back-tagline',
      name: 'Back Tagline',
      type: 'text',
      x: 6,
      y: 15,
      width: 51.5,
      height: 6,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      zIndex: 3,
      pageId: 'page-back',
      text: 'Expected return equals risk-free rate plus systematic risk premium.',
      fontFamily: 'Inter',
      fontSize: 6,
      fontWeight: '500',
      fontStyle: 'italic',
      textAlign: 'center',
      lineHeight: 1.3,
      letterSpacing: 0,
      fill: { type: 'solid', color: '#4338ca', opacity: 1 },
      stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      placeholder: {
        isPlaceholder: true,
        name: 'back_tagline',
        description: 'Tagline or summary takeaway on back side',
        defaultValue: 'Expected return equals risk-free rate plus systematic risk premium.',
      },
    },
    // Core Formula Box
    {
      id: 'poker-back-formula-bg',
      name: 'Formula Banner',
      type: 'rect',
      x: 6,
      y: 23,
      width: 51.5,
      height: 12,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      zIndex: 4,
      pageId: 'page-back',
      rx: 2,
      ry: 2,
      fill: { type: 'solid', color: '#f5f3ff', opacity: 1 },
      stroke: { type: 'solid', color: '#c4b5fd', width: 0.4, opacity: 1 },
    },
    {
      id: 'poker-back-formula-text',
      name: 'Formula Text',
      type: 'text',
      x: 8,
      y: 26.5,
      width: 47.5,
      height: 6,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      zIndex: 5,
      pageId: 'page-back',
      text: 'E(R_i) = R_f + β_i × [E(R_m) - R_f]',
      fontFamily: 'Courier New',
      fontSize: 7.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textAlign: 'center',
      lineHeight: 1.2,
      letterSpacing: 0.2,
      fill: { type: 'solid', color: '#4c1d95', opacity: 1 },
      stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      placeholder: {
        isPlaceholder: true,
        name: 'back_formula',
        description: 'Key mathematical or economic formula on back side',
        defaultValue: 'E(R_i) = R_f + β_i × [E(R_m) - R_f]',
      },
    },
    // Bullet Points
    {
      id: 'poker-back-bullets',
      name: 'Key Points',
      type: 'text',
      x: 6,
      y: 38,
      width: 51.5,
      height: 26,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      zIndex: 6,
      pageId: 'page-back',
      text: '• R_f = Risk-free rate (e.g. 10-Yr Gov Bond)\n• β_i = Beta: Sensitivity to market risk\n• [E(R_m) - R_f] = Market Risk Premium\n• If β = 1.5, asset moves 1.5× with market.',
      fontFamily: 'Inter',
      fontSize: 6.5,
      fontWeight: 'normal',
      fontStyle: 'normal',
      textAlign: 'left',
      lineHeight: 1.4,
      letterSpacing: 0,
      fill: { type: 'solid', color: '#1e293b', opacity: 1 },
      stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
      placeholder: {
        isPlaceholder: true,
        name: 'back_key_points',
        description: 'Detailed explanation bullet points on back side',
        defaultValue: '• R_f = Risk-free rate\n• β = Beta systematic risk sensitivity',
      },
    },
    // Mnemonic tip box
    {
      id: 'poker-back-tip-bg',
      name: 'Tip Callout',
      type: 'rect',
      x: 6,
      y: 66,
      width: 51.5,
      height: 16,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      zIndex: 7,
      pageId: 'page-back',
      rx: 2,
      ry: 2,
      fill: { type: 'solid', color: '#fef3c7', opacity: 1 },
      stroke: { type: 'solid', color: '#fde68a', width: 0.4, opacity: 1 },
    },
    {
      id: 'poker-back-tip-text',
      name: 'Tip Text',
      type: 'text',
      x: 8,
      y: 69,
      width: 47.5,
      height: 10,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      zIndex: 8,
      pageId: 'page-back',
      text: 'KEY TRICK: Only systematic (undiversifiable) risk is rewarded with a return premium.',
      fontFamily: 'Inter',
      fontSize: 5.5,
      fontWeight: '600',
      fontStyle: 'normal',
      textAlign: 'left',
      lineHeight: 1.3,
      letterSpacing: 0,
      fill: { type: 'solid', color: '#92400e', opacity: 1 },
      stroke: { type: 'none', color: '#000', width: 0, opacity: 0 },
    },
  ];

  return {
    id: 'tpl-poker-card-' + Date.now(),
    name: 'Creator Poker Card (Two-Sided)',
    version: '1.0.0',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    unit: 'mm',
    page: {
      preset: 'PokerCard',
      width: 63.5,
      height: 88.9,
      orientation: 'portrait',
      margins: { top: 3, right: 3, bottom: 3, left: 3 },
    },
    grid: { show: true, spacing: 5, snap: true },
    snap: { enabled: true, snapToGrid: true, snapToPage: true, snapToObjects: true, thresholdMm: 1.5 },
    objects: frontObjects,
    pages: [
      { id: 'page-front', name: 'Front Side', objects: frontObjects },
      { id: 'page-back', name: 'Back Side', objects: backObjects },
    ],
    activePageIndex: 0,
  };
}

export const TEMPLATES_LIBRARY: TemplateDefinition[] = [
  {
    id: 'cert-achievement',
    name: 'Certificate of Achievement',
    category: 'Certificate',
    description: 'Elegant A4 certificate with golden seal and awardee placeholders.',
    thumbnailIcon: 'Award',
    preset: 'A4',
    orientation: 'portrait',
    unit: 'mm',
    createDocument: createCertificateTemplate,
  },
  {
    id: 'resume-executive',
    name: 'Modern Executive Resume',
    category: 'Resume',
    description: 'Clean single-page A4 CV with career summary, roles, and skills.',
    thumbnailIcon: 'FileText',
    preset: 'A4',
    orientation: 'portrait',
    unit: 'mm',
    createDocument: createResumeTemplate,
  },
  {
    id: 'invoice-commercial',
    name: 'Commercial Bill / Invoice',
    category: 'Invoice',
    description: 'Professional invoice with line item table, totals, and client details.',
    thumbnailIcon: 'Receipt',
    preset: 'A4',
    orientation: 'portrait',
    unit: 'mm',
    createDocument: createInvoiceTemplate,
  },
  {
    id: 'yaadcard-a3-sheet',
    name: 'YaadCard 27 Flashcards (A3 Sheet)',
    category: 'Flashcard',
    description: 'Exact 27-card grid on A3 Landscape sheet (5cm × 9.5cm cards with cut lines).',
    thumbnailIcon: 'Grid',
    preset: 'A3',
    orientation: 'landscape',
    unit: 'mm',
    createDocument: createYaadCardA3SheetTemplate,
  },
  {
    id: 'yaadcard-single',
    name: 'YaadCard Flashcard (5cm × 9.5cm)',
    category: 'Flashcard',
    description: 'Single high-yield 5cm × 9.5cm study flashcard with mnemonic hook.',
    thumbnailIcon: 'BookOpen',
    preset: 'YaadCard5x9.5',
    orientation: 'portrait',
    unit: 'mm',
    createDocument: createYaadCardSingleTemplate,
  },
  {
    id: 'poker-card-creator',
    name: 'Creator Poker Card (Two-Sided)',
    category: 'PokerCard',
    description: 'Standard 2.5" × 3.5" poker card with Front (concept) and Back (solution).',
    thumbnailIcon: 'Layers',
    preset: 'PokerCard',
    orientation: 'portrait',
    unit: 'mm',
    createDocument: createPokerCardTemplate,
  },
];
